### ISSUE TITLE
Sheet References not working

### ISSUE THREAD

**Issue by dr2okevin** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#984] opened 2020-08-27 15:19 UTC
The sheet refernces described at https://docs.typo3.org/m/typo3/reference-coreapi/10.4/en-us/DataFormats/T3datastructure/SheetReferences/Index.html don't work at all. I have taken a look into TYPO3\CMS\Backend\Form\Container and its flexForm classes, and couldn't find any code that looks like it includes something

my test Flexform was
`<?xml version="1.0" encoding="utf-8"?>
<T3DataStructure>
    <sheets>
        <list>Sheets/ListSheet.xml</list>
        <show>Sheets/ShowSheet.xml</show>
    </sheets>
</T3DataStructure>`

which creates the following error
PHP Warning: Illegal string offset 'ROOT' in typo3/sysext/backend/Classes/Form/Container/FlexFormTabsContainer.php line 66

![grafik](https://user-images.githubusercontent.com/1845792/91461416-42f90100-e889-11ea-9457-71d19d41618d.png)

**Comment by susannemoog** [comment] 2020-10-08 06:29
Hey,
thanks for your report - this looks like a core issue (missing implementation, regression). Can you please open a ticket on https://forge.typo3.org/projects/typo3cms-core/issues/new ? Thank you!

**Comment by linawolf** [comment] 2020-12-24 09:31
I can find no information that this ever worked. The information got imported with the initial import of reST files. I would vote for dropping it

**Comment by linawolf** [comment] 2021-02-23 20:55
merged

**Closed by linawolf** 2021-02-23 20:55 UTC
