### ISSUE TITLE
Term disambiguation: "distribution"

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#1384] opened 2021-05-03 10:10 UTC
Topic: term, term definition, glossary

----

My suggestion would be to use "Composer project template" for meaning 1, "Composer project" for meaning 2 ~~and rethink the term distribution for meaning 3~~. But this requires some pretty nasty, breaking renaming. 

----

The term "distribution" currently has several meanings in the TYPO3 world.

1. A composer project **template**, e.g. like the [typo3/base-distribution](https://packagist.org/packages/typo3/cms-base-distribution). In the Drupal world, you would call this a [Composer project template](https://www.drupal.org/docs/develop/using-composer/starting-a-site-using-drupal-composer-project-templates)
2. A composer project (not the template, but something you typically created from the template), e.g. https://github.com/helhum/TYPO3-Distribution or https://gitlab.typo3.org/services/t3o-sites/typo3.org/typo3.org
3. an extension, which is a distribution in the sense [Creating a new Distribution](https://docs.typo3.org/m/typo3/reference-coreapi/10.4/en-us/ExtensionArchitecture/CreateNewDistribution/Index.html), e.g. "introduction package" [EXT:introduction](https://extensions.typo3.org/extension/introduction)

> Distributions are full TYPO3 CMS websites ready to be unpacked.

This is really misleading, because we are talking about an extension which requires an already installed TYPO3.

## Related issues:

* https://github.com/TYPO3-Documentation/T3DocTeam/issues/77

**Comment by sypets** [comment] 2021-05-03 10:11
@flicstar What do you think?

**Comment by flicstar** [comment] 2021-05-04 22:49
I agree with your suggestions @sypets. I'm scared about the breaking renaming - would that only be in the docs, or is it broader than that?

**Comment by sypets** [comment] 2021-05-05 08:33
@flicstar about breaking renaming: This depends (see below). I thought it might be good to hear some thoughts if others agree with me first, if this is even considered a problem and is worth the effort (_unfortunately, there will always be some effort in renaming and some disruption_).

---

I think it is a good way, the way the core does it: first something is deprecated, later it is removed or changed (breaking).

---

Having to rename stuff depends on if and how we change the use of the terms. 

For example, if we use "(Composer) project template" instead of "distribution" for meaning 1 (see above), it would make sense to rename the [typo3/cms-base-distribution](https://packagist.org/packages/typo3/cms-base-distribution) (or rather create a new package and abandon the old), e.g.:

* first, only the description is changed
* at some point the repository in GitHub and Composer package name can be changed (this requires change in docs, but not a lot). The old package can be abandoned (this will result in a message from composer pointing out the new package), e.g. see https://stackoverflow.com/questions/55378780/how-to-rename-a-php-package-in-packagist.

(Just some ideas - I am sure others could contribute more to this.)

**Comment by mbrodala** [comment] 2021-05-05 08:40
So to get this clear:

1. `typo3/base-distribution` would be a project template and be renamed to `typo3/base-project` or `typo3/project-template`?
2. `acme/foo-distribution` would be a project and be renamed to `acme/foo-project` or `acme/typo3-foo-project`?
3. `acme/foo-site` would be a site package

Notice that the "Distribution packages" in TYPO3 are basically site packages but from an era predating (Composer) site packages.

**Comment by sypets** [comment] 2021-05-05 08:41
Example:

```
composer require bitmotion/secure-downloads
```

shows message

> Package bitmotion/secure-downloads is abandoned, you should avoid using it. Use leuchtfeuer/secure-downloads instead.

I am hoping this would also happen (once it is abandoned) if you do

```
composer create-project typo3/cms-base-distribution YourNewProjectFolder
```
as described here: https://docs.typo3.org/m/typo3/guide-installation/10.4/en-us/QuickInstall/Composer/Index.html#install-typo3-via-composer

You could then point to  `typo3/cms-base-project-template`.

Changing that in the docs is not a big deal.

But the `typo3/cms-base-distribution` is probably referred to in several other places.

---

Personally, I hate making these kind of changes (and even raising this issue). It is messy. But the question is if it is worth it - will it be less confusing and more clear in the future?

**Comment by mbrodala** [comment] 2021-05-05 08:43
Symfony makes use of the term "skeleton" which clearly describes the purpose but may be scary for some:

https://packagist.org/packages/symfony/skeleton
https://packagist.org/packages/symfony/website-skeleton

**Comment by sypets** [comment] 2021-05-05 08:46
:skull: :ghost:

**Comment by linawolf** [comment] 2021-12-19 07:44
@sypets are you still working on this one?

**Comment by sypets** [comment] 2021-12-19 10:10
I am not working on this currently. This is not assigned to anyone. It is a tricky thing where not just one person should decide. 

So, I think it is still a problem but no one is working on it.

**Comment by linawolf** [comment] 2021-12-19 10:15
If it is not important enought for anyone to work on this, we just cannot provide anything better here. Feel free to to provide a PR anytime.

**Comment by linawolf** [comment] 2023-06-23 09:59
duplicate of https://github.com/TYPO3-Documentation/T3DocTeam/issues/77

**Closed by linawolf** 2023-06-23 09:59 UTC
