### ISSUE TITLE
Table too wide (gets scrollbars) on Docs » Data Formats » <T3DataStructure> » Elements

### ISSUE THREAD

**Issue by cweiske** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#62] opened 2016-05-25 09:07 UTC
The table "Elements nesting other elements (“Array” elements)" has horizontal scrollbars at
https://docs.typo3.org/typo3cms/CoreApiReference/DataFormats/T3datastructure/Elements/Index.html

which you don't see until you scroll down to the end of the table.

There is no reason for it to have scrollbars.

![2016-05-25 auswahl_001](https://cloud.githubusercontent.com/assets/59036/15534393/df84ad3a-2268-11e6-8a1a-f81c41a03286.png)

**Comment by marble** [comment] 2016-05-25 10:18
Many thanks for reporting. The problem is already known and has been noted here: https://github.com/TYPO3-Documentation/t3SphinxThemeRtd/issues/22 I've linked your problem report there. It is a problem with the CSS of the theme and should be fixed with a new release of the theme.

**Closed by marble** 2016-05-25 10:18 UTC
