### ISSUE TITLE
oudated section about ajax in backend

### ISSUE THREAD

**Issue by tmotyl** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#61] opened 2016-05-18 14:20 UTC
Section about ajax in BE is outdated:
https://docs.typo3.org/typo3cms/CoreApiReference/JavaScript/Ajax/Backend/Index.html

In version 8, the AjaxRequestHandler and  registerAjaxHandler were deprecated:
https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/core/Documentation/Changelog/8.0/Deprecation-73352-DeprecateOld-schoolAJAXRequests.rst
https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/core/Documentation/Changelog/8.1/Deprecation-75340-MethodsRelatedToGeneratingTraditionalBackendAJAXURLs.rst
https://docs.typo3.org/typo3cms/extensions/core/Changelog/7.5/Feature-65493-BackendRouting.html

**Comment by sypets** [comment] 2018-05-16 08:40
This is now the correct link: https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/JavaScript/Ajax/Backend/Index.html

"Developing with AJAX in the TYPO3 Backend" contains the note "This section is fully updated and reflects TYPO3 CMS 9.0. For older versions, please refer to the corresponding version of this manual." but no content.

**Comment by sypets** [comment] 2018-05-16 08:40
See also #262

**Comment by sypets** [comment] 2018-11-08 12:00
see also: https://docs.typo3.org/typo3cms/extensions/core/latest/Changelog/7.6/Breaking-69916-RegisteredAJAXHandlersReplacedByRoutes.html

**Comment by lolli42** [comment] 2018-11-09 10:45
Cool. Thanks Sybille! I guess we could close here, then.

**Comment by sypets** [comment] 2018-11-09 13:08
@lolli42 Actually, I closed the other 2 issues that were more or less duplicates of this one.  And now there are none, but the issue is not done. I'm reopening this one. Sorry about the confusion caused by dups.

**Comment by linawolf** [comment] 2021-01-24 11:14
@tmotyl Can you provide a PR for this topic?

**Comment by linawolf** [comment] 2021-02-23 12:15
@lolli42 can you help with this issue maybe? Would hate to close it.

**Comment by linawolf** [comment] 2021-12-19 07:42
closed: lack of feedback

**Closed by linawolf** 2021-12-19 07:42 UTC
Labels: enhancement

**Comment by sypets** [comment] 2021-12-19 10:11
@linawolf Are you closing due to lack of feedback because issue is unclear or because no one is willing to do it right now?

If it is still a problem, can we leave these kind of issues open?

**Comment by linawolf** [comment] 2021-12-19 10:13
no one gave feedback since almost a year. feel free to provide a PR anytime
